// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBGuhvSMzLb8NSqspw2kM9B2zmAXdxN9eY',
    appId: '1:1041181679576:web:b63cac450f5186deab1cad',
    messagingSenderId: '1041181679576',
    projectId: 'habitat-app-622dd',
    authDomain: 'habitat-app-622dd.firebaseapp.com',
    storageBucket: 'habitat-app-622dd.firebasestorage.app',
    measurementId: 'G-8FXH0QS2NE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvvXyZwmfEWEZruXaIrgUc3sdgcHM8k8k',
    appId: '1:1041181679576:android:07972b3490549b84ab1cad',
    messagingSenderId: '1041181679576',
    projectId: 'habitat-app-622dd',
    storageBucket: 'habitat-app-622dd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-rDLwfcg7dIq2SUwVy-OdHjOk9NKuGyc',
    appId: '1:1041181679576:ios:6faaf09d53d75c49ab1cad',
    messagingSenderId: '1041181679576',
    projectId: 'habitat-app-622dd',
    storageBucket: 'habitat-app-622dd.firebasestorage.app',
    iosBundleId: 'com.example.habitatApplication',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-rDLwfcg7dIq2SUwVy-OdHjOk9NKuGyc',
    appId: '1:1041181679576:ios:6faaf09d53d75c49ab1cad',
    messagingSenderId: '1041181679576',
    projectId: 'habitat-app-622dd',
    storageBucket: 'habitat-app-622dd.firebasestorage.app',
    iosBundleId: 'com.example.habitatApplication',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBGuhvSMzLb8NSqspw2kM9B2zmAXdxN9eY',
    appId: '1:1041181679576:web:24559090a1b7755fab1cad',
    messagingSenderId: '1041181679576',
    projectId: 'habitat-app-622dd',
    authDomain: 'habitat-app-622dd.firebaseapp.com',
    storageBucket: 'habitat-app-622dd.firebasestorage.app',
    measurementId: 'G-LFTHJ2TTL1',
  );
}
